## <p style="background-color:#14274C; font-family:Montserrat; color:#8BD5EA; font-size:150%; text-align:center; border-radius:10px 10px; margin-bottom: -15px;"><strong>AN√ÅLISE EXPLORAT√ìRIA DE CHURN DO BLUE BANK</strong></p>

<p align="center">
  <img src="../03-Recursos/churn.jpg" alt="Churn Analysis" width="600"/>
</p>

<div style="font-family: Montserrat; color:#14274C; background-color:#D2E0E9; border-radius:12px 12px;">

## <p style="background-color:#14274C; font-family:Montserrat; color:#8BD5EA; font-size:150%; text-align:center; border-radius:10px 10px; margin-bottom: -15px;"><strong>SUM√ÅRIO</strong></p>

[<p style="background-color:#14274C; font-family:Montserrat; font-size:120%; text-align:left; border-radius:10px 10px; padding-left: 50px; margin-bottom: -20px;"><strong><span style="color:#8BD5EA">1. INTRODU√á√ÉO üöÄ</span></strong></p>](#1) <br>

[<p style="background-color:#14274C; font-family:Montserrat; font-size:120%; text-align:left; border-radius:10px 10px; padding-left: 50px; margin-bottom: -20px;"><strong><span style="color:#8BD5EA">2. OBJETIVO üéØ</span></strong></p>](#2) <br>
    
[<p style="background-color:#14274C; font-family:Montserrat; font-size:120%; text-align:left; border-radius:10px 10px; padding-left: 50px; margin-bottom: -20px;"><strong><span style="color:#8BD5EA">3. IMPORTA√á√ÉO DE BIBLIOTECAS üìö</span></strong></p>](#3) <br>

[<p style="background-color:#14274C; font-family:Montserrat; font-size:120%; text-align:left; border-radius:10px 10px; padding-left: 50px; margin-bottom: -20px;"><strong><span style="color:#8BD5EA">4. CARREGAMENTO DOS DADOS üîÑ</span></strong></p>](#4) <br> 

[<p style="background-color:#14274C; font-family:Montserrat; font-size:120%; text-align:left; border-radius:10px 10px; padding-left: 50px; margin-bottom: -20px;"><strong><span style="color:#8BD5EA">5. LIMPEZA E PR√â-PROCESSAMENTO DOS DADOS üîç</span></strong></p>](#5) <br> 
    
[<p style="background-color:#14274C; font-family:Montserrat; font-size:120%; text-align:left; border-radius:10px 10px; padding-left: 50px; margin-bottom: -20px;"><strong><span style="color:#8BD5EA">6. AN√ÅLISE EXPLORAT√ìRIA DE DADOS (AED/EDA) üí°</span></strong></p>](#6) <br> 

[<p style="background-color:#14274C; font-family:Montserrat; font-size:120%; text-align:left; border-radius:10px 10px; padding-left: 50px; margin-bottom: -20px;"><strong><span style="color:#8BD5EA">7. INSIGHTS E CONCLUS√ïES üìä</span></strong></p>](#7) <br>

[<p style="background-color:#14274C; font-family:Montserrat; font-size:120%; text-align:left; border-radius:10px 10px; padding-left: 50px; margin-bottom: -20px;"><strong><span style="color:#8BD5EA">8. RECOMENDA√á√ïES üìù</span></strong></p>](#8) <br> 

[<p style="background-color:#14274C; font-family:Montserrat; font-size:120%; text-align:left; border-radius:10px 10px; padding-left: 50px; margin-bottom: -20px;"><strong><span style="color:#8BD5EA">9. CONCLUS√ÉO üèÅ</span></strong></p>](#9) <br>

<div style="font-family: Montserrat; color:#14274C; background-color:#D2E0E9; border-radius:12px 12px;">  <a id="1"></a> 

## <p style="background-color:#14274C; font-family:Montserrat; color:#8BD5EA; font-size:150%; text-align:left; border-radius:10px 10px; margin-bottom: -25px; padding-left: 75px;"><strong>1. INTRODU√á√ÉO üöÄ</strong></p>
    
- **Este projeto de An√°lise de Churn do Blue Bank tem como objetivo explorar e analisar o comportamento dos clientes do banco para identificar os principais fatores que influenciam suas decis√µes de permanecer ou deixar o banco. O conjunto de dados utilizado cont√©m informa√ß√µes diversas sobre os clientes, como idade, saldo banc√°rio, status de membro ativo, n√∫mero de produtos, e possibilidade de churn, entre outros. A descri√ß√£o detalhada de cada uma das colunas ser√° abordada na se√ß√£o de Limpeza e Pr√©-processamento dos Dados.**

<div style="font-family: Montserrat; color:#14274C; background-color:#D2E0E9; border-radius:12px 12px;">  <a id="2"></a> 

## <p style="background-color:#14274C; font-family:Montserrat; color:#8BD5EA; font-size:150%; text-align:left; border-radius:10px 10px; margin-bottom: -25px; padding-left: 75px;"><strong>2. OBJETIVO  üéØ</strong></p>

- **O objetivo principal deste projeto √© conduzir uma An√°lise Explorat√≥ria de Dados (EDA) sobre o conjunto de dados de churn dos clientes do Blue Bank. A an√°lise busca identificar padr√µes e insights que possam explicar os fatores que influenciam os clientes a deixarem o banco. Especificamente, a an√°lise se concentrar√° em responder as seguintes perguntas de neg√≥cio:**

    - **Como caracter√≠sticas como idade, saldo banc√°rio, n√∫mero de produtos e atividade do membro impactam a probabilidade de churn dos clientes?**
    - **Existe uma correla√ß√£o entre a geografia dos clientes e suas taxas de churn?**
    - **Os clientes com cart√£o de cr√©dito s√£o mais propensos a permanecer no banco comparado aos que n√£o possuem?**
    - **Qual o impacto do sal√°rio estimado na decis√£o do cliente de permanecer ou deixar o banco?**
    - **O tempo de relacionamento com o banco (tenure) impacta a lealdade dos clientes?**
    - **Como a idade dos clientes afeta a probabilidade de sair do banco?**
    - **Comparar a taxa de churn entre clientes ativos e inativos.**
    - **O pa√≠s de origem dos clientes influencia na decis√£o de sair?**
    - **Analisar se clientes com mais produtos tendem a ser mais leais ao banco.**
    - **Existe uma rela√ß√£o entre a pontua√ß√£o de cr√©dito e a taxa de churn?**
    - **Avaliar se clientes com maior pontua√ß√£o de cr√©dito s√£o mais propensos a permanecer no banco.**
    - **Investigar a correla√ß√£o entre o sal√°rio estimado e a reten√ß√£o.**
    - **O banco est√° perdendo mais clientes em algum grupo espec√≠fico (idade, pa√≠s, g√™nero)?**
    - **Tra√ßar o perfil dos clientes do banco no geral.**

- **Essas perguntas visam descobrir oportunidades para o Blue Bank aprimorar suas estrat√©gias de reten√ß√£o de clientes, oferecendo insights valiosos que podem ser utilizados para reduzir a taxa de churn e melhorar a satisfa√ß√£o geral do cliente.**

<div style="font-family: Montserrat; color:#14274C; background-color:#D2E0E9; border-radius:12px 12px;">  <a id="3"></a> 

## <p style="background-color:#14274C; font-family:Montserrat; color:#8BD5EA; font-size:150%; text-align:left; border-radius:10px 10px; margin-bottom: -25px; padding-left: 75px;"><strong>3. IMPORTA√á√ÉO DE BIBLIOTECAS E CONFIGURA√á√ÉO DE ESTILO üìö</strong></p>

- **Nesta se√ß√£o, importamos todas as bibliotecas essenciais para a execu√ß√£o da an√°lise de dados, como Pandas, Matplotlib, Seaborn e NumPy, que s√£o fundamentais para a manipula√ß√£o de dados, visualiza√ß√£o e an√°lise estat√≠stica. Adicionalmente, configuramos estilos visuais para assegurar que todas as visualiza√ß√µes sejam consistentes e reflitam a identidade visual do Blue Bank, utilizando uma paleta de cores em tons de azul. Al√©m disso, exibimos as vers√µes de cada biblioteca utilizada para garantir a reprodutibilidade e documenta√ß√£o do ambiente de desenvolvimento.**

In [1]:
import pandas as pd
import matplotlib
import seaborn as sns
import numpy as np
from platform import python_version

# Configura√ß√£o de estilos visuais para os gr√°ficos
sns.set(style="whitegrid")  # Define o estilo do Seaborn para melhor visualiza√ß√£o
blue_palette = sns.color_palette("Blues")  # Cria uma paleta de cores em tons de azul
sns.set_palette(blue_palette)  # Aplica a paleta de cores aos gr√°ficos

# Tabela de vers√µes das bibliotecas e do Python
library_versions = {
    "Pandas": pd.__version__,
    "Matplotlib": matplotlib.__version__,
    "Seaborn": sns.__version__,
    "NumPy": np.__version__
}

# Exibindo as vers√µes das bibliotecas
print("Vers√µes das Bibliotecas:\n")
print(f"{'Biblioteca':<20} | {'Vers√£o':>10}")
for nome, versao in library_versions.items():
    print(f"{nome:<20} | {versao:>10}")

# Vers√£o do Python
print("\nVers√£o do Python:")
print(python_version())

Vers√µes das Bibliotecas:

Biblioteca           |     Vers√£o
Pandas               |      1.5.3
Matplotlib           |      3.7.1
Seaborn              |     0.12.2
NumPy                |     1.24.3

Vers√£o do Python:
3.11.4

<div style="font-family: Montserrat; color:#14274C; background-color:#D2E0E9; border-radius:12px 12px;">  <a id="4"></a> 

## <p style="background-color:#14274C; font-family:Montserrat; color:#8BD5EA; font-size:150%; text-align:left; border-radius:10px 10px; margin-bottom: -25px; padding-left: 75px;"><strong>4. CARREGAMENTO DOS DADOS üîÑ</strong></p>

- **Nesta se√ß√£o, carregamos o conjunto de dados do Blue Bank, que cont√©m informa√ß√µes detalhadas sobre os clientes e seus status de churn. Este passo √© crucial para come√ßar a nossa an√°lise explorat√≥ria.**

In [2]:
# Carregando os dados do arquivo CSV
data_path = "../01-Base-de-Dados/blue-bank-churn.csv"  # Caminho da pasta com arquivo de an√°lise
df = pd.read_csv(data_path)

# Exibindo as primeiras linhas do DataFrame para verificar a importa√ß√£o
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Exibindo informa√ß√µes b√°sicas sobre o DataFrame para entender a estrutura dos dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

<div style="font-family: Montserrat; color:#14274C; background-color:#D2E0E9; border-radius:12px 12px;">  <a id="5"></a> 

## <p style="background-color:#14274C; font-family:Montserrat; color:#8BD5EA; font-size:150%; text-align:left; border-radius:10px 10px; margin-bottom: -25px; padding-left: 75px;"><strong>5. LIMPEZA E PR√â-PROCESSAMENTO DOS DADOS üîç</strong></p>

- **Antes de iniciar a an√°lise explorat√≥ria, √© essencial garantir que os dados estejam limpos e bem formatados. Esta se√ß√£o aborda a limpeza de dados, tratamento de valores nulos, corre√ß√£o de tipos de dados e qualquer outra transforma√ß√£o necess√°ria para preparar o dataset. Estas etapas s√£o cruciais para garantir a qualidade e precis√£o das an√°lises subsequentes.**

In [4]:
#Exibi√ß√£o do Dataframe atual para avaliarmos poss√≠veis mudan√ßas:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
# Dicion√°rio com as descri√ß√µes detalhadas das colunas do DataFrame. Esta informa√ß√£o √© crucial para entender o significado de cada campo e sua import√¢ncia para a an√°lise de churn.
descricao_colunas = {
    "RowNumber": "N√∫mero do registro (linha) no dataset, usado apenas como √≠ndice.",
    "CustomerId": "Identificador √∫nico do cliente no banco, crucial para identifica√ß√£o individual.",
    "Surname": "Sobrenome do cliente, n√£o tem impacto direto na an√°lise.",
    "CreditScore": "Pontua√ß√£o de cr√©dito do cliente, indicando sua solv√™ncia e potencial risco financeiro.",
    "Geography": "Pa√≠s de resid√™ncia do cliente, importante para an√°lise regional de churn.",
    "Gender": "G√™nero do cliente, √∫til para an√°lise demogr√°fica.",
    "Age": "Idade do cliente, um fator significativo na decis√£o de produtos banc√°rios.",
    "Tenure": "N√∫mero de anos que o cliente est√° com o banco, indicativo de lealdade e satisfa√ß√£o.",
    "Balance": "Saldo atual na conta banc√°ria do cliente, pode indicar satisfa√ß√£o com o banco.",
    "NumOfProducts": "N√∫mero de produtos banc√°rios que o cliente utiliza, reflete a profundidade do relacionamento.",
    "HasCrCard": "Indica se o cliente possui um cart√£o de cr√©dito (1 = Sim, 0 = N√£o), relevante para servi√ßos cruzados.",
    "IsActiveMember": "Indica se o cliente √© um membro ativo (1 = Sim, 0 = N√£o), importante para engajamento.",
    "EstimatedSalary": "Sal√°rio estimado anual do cliente, correlaciona com potencial de investimento.",
    "Exited": "Indica se o cliente deixou o banco (1 = Sim, 0 = N√£o), vari√°vel-alvo para an√°lise de churn."
}

# Convertendo o dicion√°rio em um DataFrame para facilitar a visualiza√ß√£o e entendimento das colunas
df_descricao_colunas = pd.DataFrame(list(descricao_colunas.items()), columns=['Coluna', 'Descri√ß√£o'])

# Exibindo o DataFrame para visualiza√ß√£o das descri√ß√µes das colunas
df_descricao_colunas

             Coluna                                          Descri√ß√£o
0         RowNumber  N√∫mero do registro (linha) no dataset, usado a...
1        CustomerId  Identificador √∫nico do cliente no banco, cruci...
2           Surname  Sobrenome do cliente, n√£o tem impacto direto n...
3       CreditScore  Pontua√ß√£o de cr√©dito do cliente, indicando sua...
4         Geography  Pa√≠s de resid√™ncia do cliente, importante para...
5            Gender  G√™nero do cliente, √∫til para an√°lise demogr√°fica.
6               Age  Idade do cliente, um fator significativo na de...
7            Tenure  N√∫mero de anos que o cliente est√° com o banco,...
8           Balance  Saldo atual na conta banc√°ria do cliente, pode...
9     NumOfProducts  N√∫mero de produtos banc√°rios que o cliente uti...
10        HasCrCard  Indica se o cliente possui um cart√£o de cr√©dit...
11   IsActiveMember  Indica se o cliente √© um membro ativo (1 = Sim...
12  EstimatedSalary  Sal√°rio estimado anual do cliente, correlacion...
13           Exited  Indica se o cliente deixou o banco (1 = Sim, 0...

In [6]:
# Exibindo a soma de valores nulos para cada coluna no DataFrame
null_values = df.isnull().sum()

# Verificando se h√° valores nulos e exibindo os resultados
print("Quantidade de valores nulos por coluna no dataset:")
print(null_values)

Quantidade de valores nulos por coluna no dataset:
RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
# Renomeando as colunas do DataFrame para nomes em portugu√™s com estilo snake_case
colunas_traduzidas = {
    'RowNumber': 'numero_linha',
    'CustomerId': 'id_cliente',
    'Surname': 'sobrenome',
    'CreditScore': 'pontuacao_credito',
    'Geography': 'pais',
    'Gender': 'genero',
    'Age': 'idade',
    'Tenure': 'tempo_relacionamento',
    'Balance': 'saldo',
    'NumOfProducts': 'numero_produtos',
    'HasCrCard': 'possui_cartao_credito',
    'IsActiveMember': 'membro_ativo',
    'EstimatedSalary': 'salario_estimado',
    'Exited': 'saiu_banco'
}

# Aplicando as novas nomenclaturas das colunas ao DataFrame
df.rename(columns=colunas_traduzidas, inplace=True)

# Exibindo as primeiras linhas do DataFrame para verificar as novas nomenclaturas de colunas
df.head()

,numero_linha,id_cliente,sobrenome,pontuacao_credito,pais,genero,idade,tempo_relacionamento,saldo,numero_produtos,possui_cartao_credito,membro_ativo,salario_estimado,saiu_banco
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [8]:
# Mostrando os valores √∫nicos presentes nas colunas 'pais' e 'genero'
print("Valores √∫nicos na coluna 'pais':", df['pais'].unique())
print("Valores √∫nicos na coluna 'genero':", df['genero'].unique())

# Dicion√°rios de tradu√ß√£o para as colunas 'pais' e 'genero'
traducao_paises = {
    'France': 'Fran√ßa',
    'Spain': 'Espanha',
    'Germany': 'Alemanha'
}

traducao_genero = {
    'Female': 'Feminino',
    'Male': 'Masculino'
}

# Aplicando as tradu√ß√µes
df['pais'] = df['pais'].map(traducao_paises)
df['genero'] = df['genero'].map(traducao_genero)

# Exibindo as primeiras linhas do DataFrame para verificar as tradu√ß√µes
print("\nAp√≥s a tradu√ß√£o:")
df[['pais', 'genero']].head()

Valores √∫nicos na coluna 'pais': ['France' 'Spain' 'Germany']
Valores √∫nicos na coluna 'genero': ['Female' 'Male']

Ap√≥s a tradu√ß√£o:

      pais    genero
0   Fran√ßa  Feminino
1  Espanha  Feminino
2   Fran√ßa  Feminino
3   Fran√ßa  Feminino
4  Espanha  Feminino

In [9]:
# Removendo colunas desnecess√°rias para a an√°lise de churn
# As colunas 'numero_linha' e 'sobrenome' s√£o removidas porque n√£o contribuem para a an√°lise ou insights sobre o churn dos clientes.

# Removendo as colunas do DataFrame
df.drop(['numero_linha', 'sobrenome'], axis=1, inplace=True)

# Exibindo as primeiras linhas do DataFrame ap√≥s a remo√ß√£o das colunas para confirmar a altera√ß√£o
print("DataFrame ap√≥s a remo√ß√£o das colunas 'numero_linha' e 'sobrenome':")
df.head()

DataFrame ap√≥s a remo√ß√£o das colunas 'numero_linha' e 'sobrenome':

,id_cliente,pontuacao_credito,pais,genero,idade,tempo_relacionamento,saldo,numero_produtos,possui_cartao_credito,membro_ativo,salario_estimado,saiu_banco
0,15634602,619,Fran√ßa,Feminino,42,2,0.00,1,1,1,101348.88,1
1,15647311,608,Espanha,Feminino,41,1,83807.86,1,0,1,112542.58,0
2,15619304,502,Fran√ßa,Feminino,42,8,159660.80,3,1,0,113931.57,1
3,15701354,699,Fran√ßa,Feminino,39,1,0.00,2,0,0,93826.63,0
4,15737888,850,Espanha,Feminino,43,2,125510.82,1,1,1,79084.10,0

In [10]:
# Atualiza√ß√£o do dicion√°rio com as descri√ß√µes das colunas do DataFrame ap√≥s as modifica√ß√µes
descricao_colunas_atualizada = {
    'id_cliente': 'Identificador √∫nico do cliente no banco, crucial para identifica√ß√£o individual.',
    'pontuacao_credito': 'Pontua√ß√£o de cr√©dito do cliente, indicando sua solv√™ncia e potencial risco financeiro.',
    'pais': 'Pa√≠s de resid√™ncia do cliente, importante para an√°lise regional de churn.',
    'genero': 'G√™nero do cliente, √∫til para an√°lise demogr√°fica.',
    'idade': 'Idade do cliente, um fator significativo na decis√£o de produtos banc√°rios.',
    'tempo_relacionamento': 'N√∫mero de anos que o cliente est√° com o banco, indicativo de lealdade e satisfa√ß√£o.',
    'saldo': 'Saldo atual na conta banc√°ria do cliente, pode indicar satisfa√ß√£o com o banco.',
    'numero_produtos': 'N√∫mero de produtos banc√°rios que o cliente utiliza, reflete a profundidade do relacionamento.',
    'possui_cartao_credito': 'Indica se o cliente possui um cart√£o de cr√©dito (1 = Sim, 0 = N√£o), relevante para servi√ßos cruzados.',
    'membro_ativo': 'Indica se o cliente √© um membro ativo (1 = Sim, 0 = N√£o), importante para engajamento.',
    'salario_estimado': 'Sal√°rio estimado anual do cliente, correlaciona com potencial de investimento.',
    'saiu_banco': 'Indica se o cliente deixou o banco (1 = Sim, 0 = N√£o), vari√°vel-alvo para an√°lise de churn.'
}

# Convertendo o dicion√°rio atualizado em um DataFrame para facilitar a visualiza√ß√£o e entendimento das colunas
df_descricao_colunas_atualizada = pd.DataFrame(list(descricao_colunas_atualizada.items()), columns=['Coluna', 'Descri√ß√£o'])

# Exibindo o DataFrame atualizado para visualiza√ß√£o das descri√ß√µes das colunas
print("Descri√ß√£o atualizada das colunas do DataFrame:")
df_descricao_colunas_atualizada

Descri√ß√£o atualizada das colunas do DataFrame:

                   Coluna                                          Descri√ß√£o
0              id_cliente  Identificador √∫nico do cliente no banco, cruci...
1       pontuacao_credito  Pontua√ß√£o de cr√©dito do cliente, indicando sua...
2                    pais  Pa√≠s de resid√™ncia do cliente, importante para...
3                  genero  G√™nero do cliente, √∫til para an√°lise demogr√°fica.
4                   idade  Idade do cliente, um fator significativo na de...
5    tempo_relacionamento  N√∫mero de anos que o cliente est√° com o banco,...
6                   saldo  Saldo atual na conta banc√°ria do cliente, pode...
7         numero_produtos  N√∫mero de produtos banc√°rios que o cliente uti...
8   possui_cartao_credito  Indica se o cliente possui um cart√£o de cr√©dit...
9            membro_ativo  Indica se o cliente √© um membro ativo (1 = Sim...
10       salario_estimado  Sal√°rio estimado anual do cliente, correlacion...
11             saiu_banco  Indica se o cliente deixou o banco (1 = Sim, 0...

<div style="font-family: Montserrat; color:#14274C; background-color:#D2E0E9; border-radius:12px 12px;">  <a id="6"></a> 

## <p style="background-color:#14274C; font-family:Montserrat; color:#8BD5EA; font-size:150%; text-align:left; border-radius:10px 10px; margin-bottom: -25px; padding-left: 75px;"><strong>6. AN√ÅLISE EXPLORAT√ìRIA DE DADOS (AED/EDA) üí°</strong></p>

- **Nesta se√ß√£o, conduziremos uma an√°lise explorat√≥ria detalhada dos dados do Blue Bank, utilizando visualiza√ß√µes gr√°ficas e estat√≠sticas descritivas para identificar padr√µes e correla√ß√µes que possam influenciar a decis√£o de um cliente em permanecer ou deixar o banco. Analisaremos vari√°veis como idade, saldo, n√∫mero de produtos, entre outros, para compreender melhor os fatores que contribuem para o churn dos clientes. Esta etapa √© fundamental para desdobrar insights que ajudar√£o na formula√ß√£o de estrat√©gias eficazes de reten√ß√£o de clientes.**
    - **Focaremos em responder √†s seguintes perguntas de neg√≥cio, que foram identificadas como cruciais para entender o churn dos clientes do Blue Bank:**
        - **Como caracter√≠sticas como idade, saldo banc√°rio, n√∫mero de produtos e atividade do membro impactam a probabilidade de churn dos clientes?**
        - **Existe uma correla√ß√£o entre a geografia dos clientes e suas taxas de churn?**
        - **Os clientes com cart√£o de cr√©dito s√£o mais propensos a permanecer no banco comparado aos que n√£o possuem?**
        - **Qual o impacto do sal√°rio estimado na decis√£o do cliente de permanecer ou deixar o banco?**
        - **O tempo de relacionamento com o banco (tenure) impacta a lealdade dos clientes?**
        - **Como a idade dos clientes afeta a probabilidade de sair do banco?**
        - **Comparar a taxa de churn entre clientes ativos e inativos.**
        - **O pa√≠s de origem dos clientes influencia na decis√£o de sair?**
        - **Analisar se clientes com mais produtos tendem a ser mais leais ao banco.**
        - **Existe uma rela√ß√£o entre a pontua√ß√£o de cr√©dito e a taxa de churn?**
        - **Avaliar se clientes com maior pontua√ß√£o de cr√©dito s√£o mais propensos a permanecer no banco.**
        - **Investigar a correla√ß√£o entre o sal√°rio estimado e a reten√ß√£o.**
        - **O banco est√° perdendo mais clientes em algum grupo espec√≠fico (idade, pa√≠s, g√™nero)?**
        - **Tra√ßar o perfil dos clientes do banco no geral.**

- **Cada uma dessas perguntas ser√° explorada individualmente, utilizando t√©cnicas de an√°lise de dados e visualiza√ß√£o para extrair insights relevantes e acion√°veis.**

<div style="font-family: Montserrat; color:#14274C; background-color:#D2E0E9; border-radius:12px 12px;">  <a id="7"></a> 

## <p style="background-color:#14274C; font-family:Montserrat; color:#8BD5EA; font-size:150%; text-align:left; border-radius:10px 10px; margin-bottom: -25px; padding-left: 75px;"><strong>7. INSIGHTS E CONCLUS√ïES üìä</strong></p>

- **Esta se√ß√£o apresenta os principais insights e conclus√µes obtidos a partir da an√°lise explorat√≥ria dos dados do Blue Bank. Os insights s√£o derivados das respostas √†s perguntas de neg√≥cio formuladas anteriormente e s√£o fundamentais para orientar as estrat√©gias de reten√ß√£o de clientes do banco.**

- **Principais Insights:**
    - üí° **Insight 1:** Descri√ß√£o do insight, incluindo quais dados foram analisados e quais resultados foram observados.
    - üí° **Insight 2:** Discuss√£o sobre como um determinado atributo ou combina√ß√£o de atributos afeta o churn dos clientes.
    - üí° **Insight 3:** An√°lise da influ√™ncia de fatores demogr√°ficos ou comportamentais no comportamento de churn.
    - üí° **Outros insights relevantes derivados da an√°lise.**

- **Conclus√µes:**
    - üí° **Conclus√£o 1:** Sum√°rio das implica√ß√µes dos insights para as opera√ß√µes e estrat√©gias do Blue Bank.
    - üí° **Conclus√£o 2:** Recomenda√ß√µes para a√ß√µes espec√≠ficas baseadas nos dados analisados.
    - üí° **Conclus√£o 3:** Sugest√µes para futuras an√°lises ou √°reas que requerem mais investiga√ß√£o detalhada.

- **Impacto Potencial:**
    - **Discutiremos o potencial impacto desses insights nas estrat√©gias de reten√ß√£o e crescimento do cliente, identificando oportunidades de melhoria e inova√ß√£o.**

<div style="font-family: Montserrat; color:#14274C; background-color:#D2E0E9; border-radius:12px 12px;">  <a id="8"></a> 

## <p style="background-color:#14274C; font-family:Montserrat; color:#8BD5EA; font-size:150%; text-align:left; border-radius:10px 10px; margin-bottom: -25px; padding-left: 75px;"><strong>8. RECOMENDA√á√ïES üìù</strong></p>

- **Baseadas nos insights derivados da an√°lise explorat√≥ria de dados, propomos as seguintes recomenda√ß√µes para o Blue Bank com o objetivo de melhorar a reten√ß√£o de clientes e reduzir as taxas de churn:**

    - üéØ **Recomenda√ß√£o 1:** Implementar estrat√©gias de engajamento direcionadas para grupos de clientes com alta probabilidade de churn identificados na an√°lise, como jovens em faixas et√°rias espec√≠ficas ou clientes com baixo n√∫mero de produtos.
    - üåç **Recomenda√ß√£o 2:** Desenvolver programas de fidelidade ou benef√≠cios adicionais para clientes em regi√µes com maiores taxas de churn, como mostrado nos dados geogr√°ficos.
    - üîç **Recomenda√ß√£o 3:** Oferecer servi√ßos financeiros personalizados que atendam √†s necessidades espec√≠ficas dos segmentos de clientes mais propensos a sair, com base na an√°lise de dados sobre saldo, produtos e atividade.
    - üìû **Recomenda√ß√£o 4:** Aumentar a comunica√ß√£o e o suporte ao cliente, especialmente para aqueles que demonstram sinais de inatividade ou descontentamento.
    - üîÑ **Recomenda√ß√£o 5:** Utilizar an√°lises preditivas para identificar sinais de churn precoce, permitindo interven√ß√µes proativas antes que o cliente decida sair.

- **Essas recomenda√ß√µes s√£o projetadas para serem implementadas de maneira faseada e avaliadas continuamente para efic√°cia, garantindo que o Blue Bank possa adaptar suas estrat√©gias conforme necess√°rio para maximizar a reten√ß√£o de clientes.**

<div style="font-family: Montserrat; color:#14274C; background-color:#D2E0E9; border-radius:12px 12px;">  <a id="9"></a> 

## <p style="background-color:#14274C; font-family:Montserrat; color:#8BD5EA; font-size:150%; text-align:left; border-radius:10px 10px; margin-bottom: -25px; padding-left: 75px;"><strong>9. CONCLUS√ÉO üèÅ</strong></p>

- **Esta se√ß√£o final resume os insights chave e as a√ß√µes recomendadas baseadas na an√°lise explorat√≥ria de dados realizada. Refletimos sobre o impacto potencial dessas a√ß√µes e consideramos os passos futuros para a continua√ß√£o da melhoria das estrat√©gias de reten√ß√£o de clientes do Blue Bank.**

- **Pontos Principais:**
    - Sum√°rio dos insights mais impactantes obtidos da an√°lise.
    - Avalia√ß√£o da resposta √†s perguntas de neg√≥cio inicialmente propostas.
    - Discuss√£o sobre a efic√°cia das recomenda√ß√µes implementadas e sugest√µes para ajustes.

- **Futuras Dire√ß√µes:**
    - Propostas para estudos adicionais baseados em lacunas identificadas durante a an√°lise.
    - Tecnologias ou metodologias emergentes que podem ser exploradas em futuras atualiza√ß√µes do projeto.

- **Agradecimentos:**
    - Express√£o de gratid√£o a todos os colaboradores e mentores que apoiaram o projeto.